export const TAB_BAR_STYLE = {
  backgroundColor: "#120d23",
  borderTopColor: "#1f1535",
  borderTopWidth: 0,
  borderRadius: 32,
  marginHorizontal: 16,
  marginBottom: 12,
  height: 72,
  position: "absolute",
  shadowColor: "#000000",
  shadowOpacity: 0.25,
  shadowOffset: { width: 0, height: 10 },
  shadowRadius: 20,
  elevation: 8,
  alignItems: "center",
  justifyContent: "center",
  alignSelf: "center",
  width: "90%",
  paddingVertical: 8,
};