export const getTabBarStyle = (theme) => ({
  backgroundColor: theme.colors.surface,
  borderTopColor: theme.colors.border,
  borderTopWidth: 0,
  borderRadius: 30,
  marginHorizontal: theme.spacing.md,
  marginBottom: theme.spacing.md,
  height: 70,
  position: "absolute",
  shadowColor: theme.shadow.soft.shadowColor,
  shadowOpacity: 0.28,
  shadowOffset: { width: 0, height: 12 },
  shadowRadius: 22,
  elevation: 10,
  alignItems: "center",
  justifyContent: "center",
  alignSelf: "center",
  width: "90%",
  paddingVertical: theme.spacing.sm,
});
