export const getTabBarStyle = (theme) => ({
  backgroundColor: theme.colors.surface,
  borderTopColor: theme.colors.border,
  borderTopWidth: 0,
  borderRadius: 32,
  marginHorizontal: 16,
  marginBottom: 12,
  height: 72,
  position: "absolute",
  shadowColor: theme.shadow.soft.shadowColor,
  shadowOpacity: theme.shadow.soft.shadowOpacity,
  shadowOffset: theme.shadow.soft.shadowOffset,
  shadowRadius: theme.shadow.soft.shadowRadius,
  elevation: theme.shadow.soft.elevation,
  alignItems: "center",
  justifyContent: "center",
  alignSelf: "center",
  width: "90%",
  paddingVertical: 0,
});